### ISSUE TITLE
Unable to override key/value names

### ISSUE THREAD

**Issue by niqdev** [jcustenborder/kafka-connect-spooldir#122]
Hello!
I've setup the connector and it works like a charm compared to the official `FileStreamSourceConnector`, but I've just realized that the key/value name overrides doesn't work as expected.
Could you please help me to identify what I'm doing wrong?

This is the the configuration
```json
{
  "name": "source-spooldir-connector",
  "config": {
    "connector.class": "com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceConnector",
    "tasks.max": "1",
    "input.path": "/data",
    "input.file.pattern": "^resources-\\d+\\.txt$",
    "finished.path": "/tmp/finished",
    "error.path": "/tmp/error",
    "topic": "public.postgres",
    "cleanup.policy": "MOVE",
    "timestamp.mode": "FILE_TIME",
    "empty.poll.wait.ms": 1000,
    "schema.generation.enabled": "true",
    "schema.generation.key.name": "com.kafka.demo.model.ResourceKey",
    "schema.generation.value.name": "com.kafka.demo.model.ResourceValue"
  }
}
```

This is a sample data
```json
{"accountId":"123","resourceType":"AAA","value":"A1"}
```

This is the key schema generated
```json
{
  "type": "record",
  "name": "Key",
  "namespace": "com.github.jcustenborder.kafka.connect.model",
  "fields": [],
  "connect.name": "com.github.jcustenborder.kafka.connect.model.Key"
}
```
and this the value schema generated
```json
{
  "type": "record",
  "name": "Value",
  "namespace": "com.github.jcustenborder.kafka.connect.model",
  "fields": [
    {
      "name": "accountId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "resourceType",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "value",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ],
  "connect.name": "com.github.jcustenborder.kafka.connect.model.Value"
}
```

While I was expecting for example to have for the values something like
```json
{
  "type": "record",
  "name": "ResourceValue",
  "namespace": "com.kafka.demo.model",
  "fields": [ ... ],
  "connect.name": "com.kafka.demo.model.ResourceValue"
}
```

Do you see anything wrong in my configuration?
Thanks

**Comment by jcustenborder** [comment]
@niqdev Can you elaborate a little more on the key value overrides? Do you mean that it's ignoring `schema.generation.key.name` and `schema.generation.value.name`? If so that could be a bug. Can you give the [2.0](https://github.com/jcustenborder/kafka-connect-spooldir/tree/2.0) a try?

Are you meaning changing what the actual schema of the data written to Kafka? 

If you trying to do key by `accountId` or `accountId` and `resourceType`? Give this a try.

```
schema.generation.key.fields=accountId
``` 
or 
```
schema.generation.key.fields=accountId,resourceType 
```

Another option is use the [schema generator](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-spooldir/sources/SpoolDirJsonSourceConnector.html#json-source-connector). In general the connector doesn't know what data types are so it assumes everything is a string. That was the safest bet when I designed it. If you run this generator it will give you an all string. Then you can disable schema generation and specify that the `accountId` is a long for example.

**Comment by niqdev** [comment]
You were super fast in answering me 😅 thanks!

> Do you mean that it's ignoring schema.generation.key.name and schema.generation.value.name?

yep

> Can you give the 2.0 a try?

Are the binaries available somewhere or I should build them from the sources? What are the breaking changes?

I'll give it a try to the other changes you suggested me!

**Comment by jcustenborder** [comment]
You would need to build it from source. It's really solid though. There are several companies working with it in production. It adds support for multiple tasks, so you could use connect distributed against a NAS for example.
