### ISSUE TITLE
Spooldir Failed to flush, timed out while waiting for producer to flush outstanding 

### ISSUE THREAD

**Issue by candalay** [jcustenborder/kafka-connect-spooldir#152]
Failed to flush, timed out while waiting for producer to flush outstanding 29861 messages
WorkerSourceTask{id=sender-1-0} Failed to commit offsets

I am receiving this error after 6-7 file. Is there way to make slow data transfer from A to B?

How it is possible to not receive this error?

thanks,

**Comment by jcustenborder** [comment]
@candalay This message isn't from the connector. It's from the connect framework. This happens when it's waiting for data to flush and it's timed out. You could try tweaking your connect worker settings. I'd look at increasing [batch.size](https://docs.confluent.io/current/installation/configuration/producer-configs.html#batch.size), [linger.ms](https://docs.confluent.io/current/installation/configuration/producer-configs.html#linger.ms), and [compression.type](https://docs.confluent.io/current/installation/configuration/producer-configs.html#compression.type). Also make sure that you are using multiple partitions. Basically you are sending data faster than connect can get it to kafka. You need to do a little tuning. 

I'd start by adding these to the worker config. NOT the connector config. I'm going to go ahead and close this. Please reopen if you run into something.

```
linger.ms=150
compression.type=lz4
send.buffer.bytes=512000
```
